### ISSUE TITLE
LFSC does not terminate when the input contains the character ’

### ISSUE THREAD

**Issue by yoni206** [CVC4/LFSC#1]
To reproduce:

- create a .plf file with the following content:
(declare clause type)
(declare holds (! c’ clause type))

- run lfscc <filename>

**Comment by ajreynol** [comment]
I was able to reproduce this.  I am not sure what character the quote in this file is.  It is not ` or ' on my keyboard.  I suppose this is an extended character?

**Comment by yoni206** [comment]
I  copied code from the lfsc paper, and that code included a " ' " in the
pdf. I can't find a matching character in my keyboard either, so yeah, I
also assume it is an extended character.

**Comment by tinelli** [comment]
I am pretty sure it was an extended character. The single quote in PDF is not the ASCII  ' .
Try 
````
(declare clause type)
(declare holds (! c😤 clause type))
````
Same thing. (And no, it does not help if you use "😀" instead ...)
This is a bug that needs fixing. This is a job for Superandy.

BTW, extended characters in comments are OK.

Cesare
