### ISSUE TITLE
Strange parsing 

### ISSUE THREAD

**Issue by tinelli** [CVC4/LFSC#20]
This is truly bizarre.  The code below produces the following error:

> Undeclared identifier at head of an application: comparx

The same kind of error is generated for any non-empty prefix of `compar` used instead of `compar` as the  name of the first program.
Using `compare` produces instead the error

> Undeclared identifier: 

with nothing after the colon. Using other names for the first program, including `compari`, produces no error.

````clojure 
(declare comparison type)
(declare SMALLER comparison)
(declare EQUAL comparison)
(declare GREATER comparison)

(program compar ((m mpz) (n mpz)) comparison
  EQUAL
)

(program p1 ((x mpz) (y mpz)) comparison
  (comparison x y)
)  
````

**Comment by tinelli** [comment]
`compare` is a reserved word? Where is it used?

**Comment by ajreynol** [comment]
`compare` is indeed a reserved word.  See bottom of page 4: http://homepage.divms.uiowa.edu/~ajreynol/report-lra-pf.pdf .

This didn't make it into the journal paper on LFSC it seems. (Moreover, this is really pointing to the fact that we need a user manual...)
